/*
    Copyright (c) 2004-2010, The Dojo Foundation All Rights Reserved.
    Available via Academic Free License >= 2.1 OR the modified BSD license.
    see: http://dojotoolkit.org/license for details
*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_dojotoolkit_rt_v8_V8JavaBridge */

#ifndef _Included_org_dojotoolkit_rt_v8_V8JavaBridge
#define _Included_org_dojotoolkit_rt_v8_V8JavaBridge
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     org_dojotoolkit_rt_v8_V8JavaBridge
	 * Method:    runScriptInV8
	 * Signature: (Ljava/lang/String;)Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_org_dojotoolkit_rt_v8_V8JavaBridge_runScriptInV8
	(JNIEnv *, jobject, jstring);
	
	/*
	 * Class:     org_dojotoolkit_rt_v8_V8JavaBridge
	 * Method:    runScriptInV8WithCallbacks
	 * Signature: (Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_org_dojotoolkit_rt_v8_V8JavaBridge_runScriptInV8WithCallbacks
	(JNIEnv *, jobject, jstring, jobjectArray);
	
	/*
	 * Class:     org_dojotoolkit_rt_v8_V8JavaBridge
	 * Method:    runScriptInV8WithExternalCallbacks
	 * Signature: (Ljava/lang/String;[Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_org_dojotoolkit_rt_v8_V8JavaBridge_runScriptInV8WithExternalCallbacks
	(JNIEnv *, jobject, jstring, jobjectArray, jobject);
	
#ifdef __cplusplus
}
#endif
#endif
